spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:qqiq;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true