INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (0, 'People''s Life', '2013-04-28', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (1, 'RICKENBACKER', '2013-05-19', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (2, 'TODAY(Before The Dawn)', '2013-06-02', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (3, 'J-ROCK RE-CREATION', '2013-06-16', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (4, '2011', '2013-07-19', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (5, 'Living Things', '2013-07-26', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (6, 'Past Times Inside', '2013-08-08', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (7, 'Perfect Suicide', '2013-08-27', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (8, 'MEKAKUSHI', '2013-09-12', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (9, 'Drawing My Youth', '2013-09-24', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (10, 'Jesus Christ''s Coming', '2013-10-26', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (11, 'KAFKA', '2013-11-28', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (12, '暇人と音楽的な美少女', '2013-12-23', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (13, 'おんらいん？ラブ', '2014-03-14', 'ねむこ', 'ねむこ');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (14, 'いけない！トライアングル', '2014-05-15', 'ねむこ', 'ねむこ');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (15, 'Don''t Call Me Crazy,Make Your Star', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (16, 'たべっこどうぶつ', '2014-03-12', '？', '？');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (17, 'びすこ なびすこ 〜ややこしや〜', '2014-04-06', '？', '？');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (18, 'Saori', '2014-06-08', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (19, 'MOTHER', '2014-05-18', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (20, 'I MISS YOU LOVE', '2014-05-25', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (21, 'Rock and Roll and Girls and Music', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (22, '432687', '2014-06-01', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (23, 'Neoteny', '2014-06-15', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (24, 'Logout', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (25, 'Daydream', '2014-06-20', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (26, 'Fei Long', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (27, 'Everything is my fault', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (28, 'She has come', '2014-08-29', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (29, 'Luvego', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (30, 'Death From Above 1999', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (31, 'Asperger Management', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (32, 'My Girl', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (33, 'River', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (34, 'Rickenbacker', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (35, 'Dancing in the Daylight', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (36, 'Mr.Meloncholy', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (37, 'Sister''s Guitar Replica', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, release_date, composer, songwriter) VALUES (38, 'with you', '2014-12-04', '橋爪 裕', '橋爪 裕');
INSERT INTO Musics (id, title, composer, songwriter) VALUES (39, 'Dancing in the Daylight', '橋爪 裕', '橋爪 裕');
